links:
- text: 'top'
  href: '/?page=top'
- text: '日誌（ブログ）'
  href: '/?post'
- text: '旧ホームページ'
  href: ''
- text: '外部サイト'
  href: './'
  sublinks:
  - text: '作者twitter'
    href: 'https://twitter.com/LichenMoss'
  - text: '株式会社環境レジリエンス'
    href: 'http://kankyo-resilience.co.jp/'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/LichenMoss'
- icon: 'fa-github-square'
  href: 'https://github.com/hirominakaji'
- icon: 'fa-graduation-cap'
  href: 'https://www.researchgate.net/profile/Hiromitsu_Nakajima2/'
