protocol: 'https:'
host: 'lichenmoss.net'
sitetitle: '白と緑のミクロの森'
sitesubtitle: '地衣類・蘚苔類と共に生きる─コケ学のススメ'
links:
- text: 'コケ学のススメ'
  href: '/?page=intro'
- text: '日誌（ブログ）'
  href: '/?post'
- text: '旧ホームページ'
  href: '/old_hp/index.html'
- text: '外部サイト'
  href: './'
  sublinks:
  - text: '作者twitter'
    href: 'https://twitter.com/LichenMoss'
  - text: '株式会社環境レジリエンス'
    href: 'http://kankyo-resilience.co.jp/'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/LichenMoss'
- icon: 'fa-github-square'
  href: 'https://github.com/hirominakaji'
- icon: 'fa-graduation-cap'
  href: 'https://www.researchgate.net/profile/Hiromitsu_Nakajima2/'
twitter: 'LichenMoss'
line: '@'
